Feature/pbgg 7
Programmers-Only-Group/projects pull request #8
Opened 2020-10-19 13:30 UTC by Piotr-Grzybowski

2020-10-19 14:08 UTC, cisowianka62 approved these changes

2020-10-19 14:19 UTC, cisowianka62 requested changes

2020-10-19 14:19 UTC, cisowianka62 commented on src/user/schemas/user.schema.ts
> +  projects: [Number]
I think we can use here populate projects

2020-10-19 14:19 UTC, cisowianka62 commented on src/projects/schemas/project.schema.ts
> +    }, { _id: false });
Here we need add field creator and contributors because now we don't have information who is creator and who is contributors

2020-10-21 21:04 UTC, Piotr-Grzybowski commented
Added contributors and creator fields and also references so we can easily get data from other collection using only single method.

2020-10-22 09:42 UTC, cisowianka62 approved these changes, later dismissed

2020-10-26 17:35 UTC, merged